export enum tagTypes {
  user = "user",
  service = "service",
  profile = "profile",
  booking = "booking",
  subject = "subject",
  faq = "faq",
  availableService = "availableService",
  feedback = "feedback",

  department = "department",
  faculty = "faculty",
  admin = "admin",
  student = "student",
  academicFaculty = "academic-faculty",
  academicDepartment = "academic-department",
  building = "building",
  room = "room",
  course = "course",
  semesterRegistration = "semester-registration",
  offeredCourse = "offered-course",
  offeredCourseSection = "offered-course-section",
  offeredCourseSchedule = "offered-course-schedule",
  courseRegistration = "course-registration",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.service,
  tagTypes.profile,
  tagTypes.booking,
  tagTypes.subject,
  tagTypes.faq,
  tagTypes.availableService,
  tagTypes.feedback,

  tagTypes.department,
  tagTypes.faculty,
  tagTypes.admin,
  tagTypes.student,
  tagTypes.academicFaculty,
  tagTypes.academicDepartment,
  tagTypes.building,
  tagTypes.room,
  tagTypes.course,
  tagTypes.semesterRegistration,
  tagTypes.offeredCourse,
  tagTypes.offeredCourseSection,
  tagTypes.offeredCourseSchedule,
  tagTypes.courseRegistration,
];
